# Sample build-and-scan/action.yml
name: Build and Scan Docker Image
description: Builds a Docker image and scans it for vulnerabilities.
inputs:
  context:
    description: 'Build context directory'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  tag:
    description: 'Docker image tag'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t ${{ inputs.tag }} -f ${{ inputs.dockerfile }} ${{ inputs.context }}

    - name: Install Trivy
      run: |
        sudo apt-get update && sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/download/v0.45.1/trivy_0.45.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.45.1_Linux-64bit.deb

    - name: Trivy Scan
      run: |
        trivy image --severity HIGH,CRITICAL ${{ inputs.tag }}
