name: 'Run Lint and Test'
description: 'A GitHub Action to run lint and tests with custom configuration'
author: 'Prakhar'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '16'
runs:
  using: 'composite'
  steps:
    - name: Run lint
      run: yarn lint --fix || true # Remove `|| true` if you want to fail on lint errors
      shell: bash

    - name: Run tests
      run: yarn test
      shell: bash
