name: 'Run Lint and Test'
description: 'A GitHub Action to run lint and tests with custom configuration'
author: 'Prakhar'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Run lint
      run: yarn lint
      shell: bash

    - name: Run tests
      run: yarn test
      shell: bash
