name: 'Node.js Lint and Test'
description: 'A composite action to lint and test a Node.js app'
author: 'Urbint'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: |
        yarn install
      shell: bash

    - name: Run Lint
      run: |
        yarn lint
      shell: bash

    - name: Run Test
      run: |
        yarn test
      shell: bash

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '16'
