name: "Install BE"
description: "Install Poetry and Python and cache poetry dependencies, install GDAL lib, run bootstrap script"
inputs:
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.9'
  poetry-version:
    description: 'Version of Poetry to install'
    required: true
    default: 'latest'
  working-directory:
    description: 'Directory to run the installation'
    required: true
    default: 'damage-prevention'
  debug:
    description: 'Debug environment variable'
    required: false
    default: 'False'
  test:
    description: 'Test environment variable'
    required: false
    default: 'True'
  ci:
    description: 'CI environment variable'
    required: false
    default: 'True'
  enable_gcs:
    description: 'Enable GCS environment variable'
    required: false
    default: 'False'
  project:
    description: 'Project name'
    required: false
    default: 'damage-prevention'
  django_settings_module:
    description: 'Django settings module'
    required: false
    default: 'core.settings'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - name: Install dependencies
      run: |
        cd ${{ inputs.working-directory }}
        poetry install
      shell: bash

    - name: Run bootstrap script
      run: |
        cd ${{ inputs.working-directory }}
        ./support/scripts/bootstrap.sh
      shell: bash

    - name: Run Black
      run: |
        cd ${{ inputs.working-directory }}
        poetry run black --check .
      shell: bash

    - name: Run Flake8
      run: |
        cd ${{ inputs.working-directory }}
        poetry run flake8 .
      shell: bash

    - name: Run isort
      run: |
        cd ${{ inputs.working-directory }}
        poetry run isort --check .
      shell: bash

    - name: Run mypy
      run: |
        cd ${{ inputs.working-directory }}
        poetry run mypy .
      shell: bash

    - name: Set environment variables
      run: |
        echo "DEBUG=${{ inputs.debug }}" >> $GITHUB_ENV
        echo "TEST=${{ inputs.test }}" >> $GITHUB_ENV
        echo "CI=${{ inputs.ci }}" >> $GITHUB_ENV
        echo "ENABLE_GCS=${{ inputs.enable_gcs }}" >> $GITHUB_ENV
        echo "PROJECT=${{ inputs.project }}" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=${{ inputs.django_settings_module }}" >> $GITHUB_ENV
      shell: bash
