name: 'Docker Push to GCR'
description: 'Builds and pushes a Docker image to Google Container Registry'
inputs:
  tag:
    description: 'Tag for the Docker image (e.g., latest or commit SHA)'
    required: true
  gcr_sa_key:
    description: 'GCP Service Account JSON key for authentication'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile (default: Dockerfile)'
    required: false
    default: 'Dockerfile'
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20' 
  registry-url:
    description: 'Registry URL for NPM packages'
    required: true
  node-auth-token:
    description: 'NPM Auth Token for accessing private packages'
    required: true
    default: '' 
  
  image_name:
    description: 'Name of the Docker image (default: my-frontend-image)'
    required: true
    default: 'my-frontend-image'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      run: |
        yarn install
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}  
      shell: bash  

    - name: Build the application
      run: |
        yarn build  # Add the build step
      shell: bash  

    - name: Push Image
      uses: urbint/CompositeAction/docker-push@main
      with:
        tag: ${{ inputs.tag }} 
        gcr_sa_key: ${{ inputs.gcr_sa_key }} 
        dockerfile: ${{ inputs.dockerfile }} 
        image_name: ${{ inputs.image_name }} 

