name: 'Docker Push to GCR'
description: 'Builds and pushes a Docker image to Google Container Registry'
inputs:
  image_name:
    description: 'Name of the Docker image to push (e.g., my-image)'
    required: true
  tag:
    description: 'Tag for the Docker image (e.g., latest or commit SHA)'
    required: true
  gcr_sa_key:
    description: 'GCP Service Account JSON key for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: "access_token"
        credentials_json: ${{ inputs.gcr_sa_key }}
    - name: Log into Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}  
  
        
    - name: Build Docker Image
      shell: bash
      run: |
        echo "Building Docker image..."
        docker build -t my-image:${{ inputs.tag }} .

    - name: Push Docker Image
      shell: bash
      run: |
        echo "Pushing Docker image to GCR..."
        docker tag my-image:${{ inputs.tag }} gcr.io/urbint-1259/${{ inputs.image_name }}:${{ inputs.tag }}
        docker push gcr.io/urbint-1259/${{ inputs.image_name }}:${{ inputs.tag }}
