name: Push Docker Image
description: Push a Docker image to Google Container Registry

inputs:
  image:
    description: 'The Docker image to push'
    required: true
  tag:
    description: 'The tag for the Docker image (default: latest)'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: "access_token"
        credentials_json: ${{ secrets.GCR_SA_KEY }}

    - name: Log into Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: gcr.io/urbint-1259/${{ inputs.image }}:${{ inputs.tag }}

branding:
  icon: "cloud"
  color: "blue"
